---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  default.conf: |
    server {
      listen 80;
      server_name ivreone.online;

      default_type text/plain;

      location / {
        return 200 '$hostname\n';
      }
    }