---
- hosts: prom
  vars_files: credentials.yml
  become: true
  remote_user: root
  tasks:

  - name: "adduser {{ item.name }}"
    user:
      name: "{{ item.name }}"
      password:
  - name: "add ssh_key {{ item.name }}" 
    authorized_key:
      user: "{{ item.name }}"
      key: "{{ item.pub_key }}"
